DROP TABLE IF EXISTS cart_items CASCADE;

CREATE TABLE cart_items (
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  dish_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
  id SERIAL PRIMARY KEY NOT NULL
);
 -- placed BOOLEAN DEFAULT FALSE
